#!/bin/bash

#param check
if [ $# -ne 1 ]; then
   echo -e "$0 Usage URL\n"
fi


echo broken links:

mkdir /tmp/$$.lynx

cd /tmp/$$.lynx

lynx -traversal $1 > /dev/null
count=0

#unique sort special file generated by -traversal and redirect to links.txt
echo "links check:"
sort -u reject.dat > links.txt

while read link
do
    output=`curl -I $link -s | grep "HTTP/.*OK"`;
    if [[ -z $output ]]; then
        echo $link
        let count++
    fi
done < links.txt

[ $count -eq 0 ] && echo No broken links found

